import { NavBar } from "~/components/NavBar";
import { Suspense } from "react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className="absolute top-0 flex min-h-screen w-svw flex-col items-center">
        {children}
      </main>
      <NavBar />
    </>
  );
}
